### ISSUE TITLE
Addon does not work after adding tag

### ISSUE THREAD

**Issue by LostGlitter3967** [SIsilicon/WorldEdit-BE#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Eu ponho a Tag worldedit mas não funciona

### Expected behaviour

Colocar a Tag worldedit e funcionar

### Steps to reproduce

/tag @s add world edit não funciona

### Minecraft version

1.19.51

### Device and operating system

Sansung android 12

**Comment by SIsilicon** [comment]
Since it's already known that the addon works fine, this isn't a bug, but an installation problem. Make sure the following has been done.
- Both Holiday Creator Features and Beta APIs (GameTest Framework) have been enabled.
- Both the behaviour and resource packs for WorldEdit 0.7.0 have been installed on the world

Closing the issue, but you can still comment to provide more detail on your problem.
